default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  user: postgres
  password: postgres

development:
  <<: *default
  database: gflix_development

test:
  <<: *default
  host: localhost
  database: db/gflix
  password: postgres